### PR TITLE
Change db summary format AGR-2121

### PR DESCRIPTION
**Pull request by adamjohnwright**
This pull request changes the return format for the JSON in the db_summary files to Objects to make things more explicit. It also has a total count for labels that have sub-labels like Ontology.

Heres is an example section of the JSON that it generates

```
{
            "counter": 8000341,
            "nodeLabel": "Association",
            "subLabels": [
                {
                    "counter": 210101,
                    "nodeLabel": "DiseaseEntityJoin"
                },
                {
                    "counter": 1517689,
                    "nodeLabel": "BioEntityGeneExpressionJoin"
                },
                {
                    "counter": 1353756,
                    "nodeLabel": "PhenotypeEntityJoin"
                },
                {
                    "counter": 2225342,
                    "nodeLabel": "OrthologyGeneJoin"
                },
                {
                    "counter": 1764317,
                    "nodeLabel": "PublicationJoin"
                },
                {
                    "counter": 929136,
                    "nodeLabel": "InteractionGeneJoin"
                }
            ]
        },

````

### CODE REVIEW

**Comment by sierra-moxon** [comment]
Is it possible to keep all node labels at the same level?  ie: Association would just be another item in the list, instead of the nesting?  

It would be ok with me if my requests generated a different file, if you need the nesting for some other purpose.

**Comment by adamjohnwright** [comment]
Just pushed a change for this. You are the first consumer as far as I am aware so you get your say first :)

it now looks like

```
       {
            "counter": 14863,
            "nodeLabel": "UBERONTerm",
            "parentLabel": "Ontology"
        },
        {
            "counter": 169868,
            "nodeLabel": "Ontology"
        },
```

**Comment by sierra-moxon** [comment]
This will probably break the loader once the first of these gets into 3.1.0 snapshot, so if possible, give me a heads up when it is in and I'll quickly pull together the code changes in the loader.  Appreciate it!  this will be much nicer to work with.

**Comment by nuin** [comment]
@sierra-moxon Am I OK to merge it?

**Pull request merged**
