### PR TITLE
Fix header

### PR DESCRIPTION
**Pull request by nuin**
Branch should be called fix headers not labels, but now it's too late

### CODE REVIEW

**Comment by nuin** [comment]
Check the Jira ticket

**Comment by adamjohnwright** [comment]
I see. In order to have this pull request tied to JIRA you would need to have it say AGR-###. This is what we normally do. I think it could also be put in the description but I am not sure. If the ID Is put in the PR correctly JIRA will do some things automatically with the ticket. Do you mind. Putting the JIRA ID in the name of the PR?

**Comment by nuin** [comment]
I will do it tomorrow, no rush. Also, it doesn't solve the ticket itself.

**Comment by nuin** [comment]
AGR-2037

**Comment by nuin** [comment]
It's connected on Jira

**Pull request merged**
