### PR TITLE
Using a Ordered Dict for the species list in header.py

### PR DESCRIPTION
**Pull request by adamjohnwright**
This code does a query to the database to get the taxon IDs and species names into an OrderedDict. From there the species for the file are ordered and then sent to the header.py. 

This cleans up what is passed to header.py

I tested this by looking at the headers that were generated for orthology, disease, and expression. They looked right to me.

I am pulling into master as the header itself is not changing and this gives a chance for the file_generator and others to use the improvements. 

@valearna and @azurebrd you could use get_ordered_species_dict but you will have to create a config_info object to perform the query. I am not sure if you want to do this or not but it would be convenient for you to use the same function. Although it woudn't be too hard to just cut and past the query into your own code.

### CODE REVIEW

**Comment by valearna** [comment]
Thanks @adamjohnwright. For gene descriptions we have a single species/taxonID for each file, so we don't really need to use the get_ordered_species_dict function, but the new create_header function simplifies the management of species/taxonIDs.

**Comment by adamjohnwright** [comment]
@azurebrd I hadn't thought of this issue before. If staging is up and it is almost always up it would produce the correct species results. That is until we add more species - it would be behind "build" until it makes it to a release branch. This is where having a persistent datastore would be quite useful. In that way the build database would be always up. I think you should try using it. If using stage's DB does not work you could always hardcode the Dict into your code as a workaround till we have a persistent store available to query.

**Comment by azurebrd** [comment]
@adamjohnwright cool cool, so setting NEO4J_HOST to stage.alliancegenome.org such that filegenerator then connects to bolt://stage.alliancegenome.org:7687 should work (It's not password protected or ip restricted or anything like that ?  I haven't used bolt:// before).  Sounds good either way, I'll try it out when we're making changes for 3.1.1, and if filegenerator doesn't work with bolt://stage I'll keep it with the local dict, or run neo when doing tests.  Thanks :)

**Comment by adamjohnwright** [comment]
@azurebrd No password. It is made available to a particular IP address'. If you can access this web console: http://stage.alliancegenome.org:7474/browser/ you are good. Then with the portal hit connect. You should then be able to query.

**Comment by oblodgett** [comment]
Not sure about this conversation but the file generator already has a connection to Neo. So it can get any data it needs. If you are talking about putting this dependency in another software repo I would suggest against it. We have files in the loader that produce this info.

**Comment by adamjohnwright** [comment]
@oblodgett I don't really know his use-case but he mentioned it being a preprocessing pipeline.

**Comment by oblodgett** [comment]
@azurebrd if that is the case please consider using the ETLHelper in the loader repo just copy the file in... I don't like this solution but the file generator is doing that already with the "files' directory. @valearna @sierra-moxon @adamjohnwright in the future we need to think about creating a "shared" module in the python world for some of this functionality so that we don't have copied and pasted code everywhere. Do it now, it only gets worse in the future.

**Comment by adamjohnwright** [comment]
@oblodgett I don't think this PR is the place to discuss this but what we are discussing is trying to avoid copying and pasting code. The gene_descriptions are using the file_generator code for headers. This a continuation of doing the same with @azurebrd 's code. I am confused on why you are suggesting not to use it.

**Comment by azurebrd** [comment]
@oblodgett The file generator is creating headers for files that users could download, and the hope is that the headers could be standardized based on a template, but any given file could have any combination of a set of 7 taxons (and their species), and the code that @adamjohnwright 's worked on queries neo for the species sorted by their phylogeneticOrder, so depending on which taxons/species exist in any given file to be generated, a set of taxons is passed to it, and a correct header with sorted taxons/species gets generated  (There's also other values to pass, but they don't require neo).  There isn't a specific file that I could get with the ETLHelper, but if I'm missing something, please let me know.  The loader repo has a neo connection open, and production also has a neo connection open, but when doing development on agr_preprocess/ I haven't needed a neo connection, and running neo has been a bit memory intensive, but I can always just run neo and it will be a bit slower.  

@adamjohnwright I don't have access to http://stage.alliancegenome.org:7474/browser/ (times out)  If you could add wobr2.caltech.edu and wobrbig.caltech.edu, that'd be great.  If you need numeric IPs, I'll have to ask Raymond whether they're static IPs.

If there's a better ticket or slack channel for this conversation, I'm happy to move there :)

**Comment by adamjohnwright** [comment]
@azurebrd Thanks for the details. I just don't think this is the right medium to have too much more conversation because I was about to pull in the PR. I also think it would be more open to have the conversation on slack. That being said feel free to send me the IP address to those machines and I will add them to the list tomorrow.

**Pull request merged**
